Cgi method
chughes741/webserv pull request #109
Opened 2023-11-17 04:52 UTC by yann1731

It's coming along

2023-11-21 03:14 UTC, francislah requested changes

2023-11-21 03:14 UTC, francislah commented on src/parsing.cpp
validateFirstToken and validateLastToken needs to be "cgi"

2023-11-21 03:14 UTC, francislah commented on html/cgi-bin/api.py
still necessary?

2023-11-21 03:20 UTC, yann1731 commented on html/cgi-bin/api.py
What do you mean?

2023-11-21 03:27 UTC, yann1731 commented on src/parsing.cpp
Fixed

2023-11-23 21:22 UTC, francislah approved these changes

2023-12-11 03:18 UTC, merged